# Generated by Django 4.0.5 on 2022-06-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_sport_result_event_alter_athlete_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.CharField(default='NA', max_length=5),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.CharField(default='NA', help_text='Measurement Unit - centimeters', max_length=5),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.CharField(default='NA', help_text='Measurement Unit - kilograms', max_length=5),
        ),
    ]
